const moduleRegistry = [
  { path: '/users', router: require('../../modules/auth/user.routes') },
  { path: '/roles', router: require('../../modules/auth/role.routes') },
  { path: '/items', router: require('../../modules/entity/item.routes') },
  { path: '/manufacturers', router: require('../../modules/entity/manufacturer.routes') },
  { path: '/brands', router: require('../../modules/entity/brand.routes') },
  { path: '/units', router: require('../../modules/master-data/units.routes') },
  { path: '/dropdown-options', router: require('../../modules/master-data/dropdownOptions.routes') },
  { path: '/categories', router: require('../../modules/entity/category.routes') },
  { path: '/warehouses', router: require('../../modules/warehouse/warehouse.routes') },
  { path: '/warehouse-types', router: require('../../modules/warehouse/warehouseType.routes') },
  { path: '/warehouse-locations', router: require('../../modules/warehouse/warehouseLocation.routes') },
  { path: '/inventory', router: require('../../modules/inventory/inventory.routes') },
  { path: '/purchase-orders', router: require('../../modules/order/purchaseOrder.routes') },
  { path: '/vendors', router: require('../../modules/entity/vendor.routes') },
  { path: '/customers', router: require('../../modules/entity/customer.routes') },
  { path: '/sales-orders', router: require('../../modules/order/salesOrder.routes') },
  { path: '/invoices', router: require('../../modules/invoice/invoice.routes') },
  { path: '/purchase-invoices', router: require('../../modules/invoice/purchaseInvoice.routes') },
  { path: '/accounting', router: require('../../modules/invoice/accounting.routes') },
  { path: '/sales-invoices', router: require('../../modules/invoice/salesInvoice.routes') },
  { path: '/grn', router: require('../../modules/order/grn.routes') },
  { path: '/reorder-levels', router: require('../../modules/inventory/reorderLevel.routes') },
  { path: '/batch-serial', router: require('../../modules/inventory/batchSerial.routes') },
  { path: '/stock-counts', router: require('../../modules/inventory/stockCount.routes') },
  { path: '/purchase-returns', router: require('../../modules/order/purchaseReturn.routes') },
  { path: '/data', router: require('../../modules/master-data/allData.routes') },
  { path: '/reports', router: require('../../modules/reports/reports.routes') },
  { path: '/profit-loss', router: require('../../modules/reports/profitLoss.routes') },
  { path: '/settings', router: require('../../modules/settings/settings.routes') },
  { path: '/company-settings', router: require('../../modules/settings/companySettings.routes') },
  { path: '/documents', router: require('../../modules/documents/document.routes') },
  { path: '/delivery-challans', router: require('../../modules/order/deliveryChallan.routes') },
  { path: '/transfer-approvals', router: require('../../modules/inventory/transferApproval.routes') },
  { path: '/analytics', router: require('../../modules/reports/analytics.routes') },
  { path: '/notifications', router: require('../../modules/notification/notification.routes') },
  { path: '/audit', router: require('../../modules/audit/audit.routes') },
  { path: '/onboarding', router: require('../../modules/onboarding/onboarding.routes') },
  { path: '/tax', router: require('../../modules/tax/tax.routes') },
  { path: '/price-lists', router: require('../../modules/price-lists/priceList.routes') },
  { path: '/production', router: require('../../modules/production/production.routes') },
  { path: '/subscription', router: require('../../modules/subscription/subscription.routes') },
  { path: '/workflows', router: require('../../modules/workflows/workflow.routes') },
  { path: '/sku-rules', router: require('../../modules/settings/skuGenerator.routes') },
];

module.exports = moduleRegistry;
